.TH NewBreeze 1 "October 9 2017"
.SH NAME
NewBreeze \- A Qt based lightweight and fast file manager
.SH SYNOPSIS
.B newbreeze
.RI [ options ] " [url]" ...
.SH DESCRIPTION
Built on top of the Powerful Qt4/Qt5 GUI Toolkit, this file manager is sleek, stylish and fast.
Some of its features are
    - Fast startup and browsing
    - Folder, text, html, image, odt, and pdf quick preview
    - File Association support
    - Provides Categorized List, Icon and Details View
    - Sleek side panel showing drives and boomarks
    - Drag and drop support (partial)
    - SuperStart and Catalog View
    - Auto update devices list
    - Custom Folder Icons and Thumbnail Preview
    - Complete mime-icon support
    - BreadCrumbs Navigation Bar
    - Custom Actions
    - Inline terminal
    - SingleApplication Mode for resource sharing
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-h, \-\-help
	Show a summary of options
.TP
.B \-u, \-\-usage
	Print the usage and exit.
.TP
.B \-m, \-\-manpage
	Show this manpage
.TP
.B \-v  \-\-version
	Print version information and exit.
.TP
.B \-t, \-\-tray
	Open an instance in system tray if not already open
.TP
.B \-s, \-\-settings
	Open the settings dialog.
.TP
.B \-a, \-\-about
	Show the about NewBreeze dialog.
.TP
.B \-l, \-\-license
	Show the NewBreeze License dialog.
.TP
.B \-f, \-\-force-new
	Kill the old server and start a new one.

.SH Examples
.TP
Print the help message and exit
newbreeze -h
.TP
Opens the last opened directory or SuperStart/Catalogs
newbreeze
.TP
Opens an instance in tray
newbreeze -t
.TP
Opens the settings dialog
newbreeze -s
.TP
Opens the settings dialog
newbreeze --settings
.TP
Opens the about NB dialog
newbreeze -a
.TP
Opens the NB license dialog
newbreeze --license
.TP
Kills the existsing server and opens window at the last opened location
newbreeze --force-new
.TP
Kills the existsing server and opens a window at /home/cosmos
newbreeze --force-new /home/cosmos
