/* This file was automatically generated by makeVer v0.2.1-1 */

#ifndef QDRIVE_VERSION_H
#define QDRIVE_VERSION_H

#include <QtCore>
#include <QString>

#define QDRIVE_VERSION_RELEASE 1
#define QDRIVE_VERSION_STRING "0.9.1-1"
#define QDRIVE_VERSION_MAJOR 0
#define QDRIVE_VERSION_PACKAGE 1
#define QDRIVE_VERSION_MINOR 9
#define QDRIVE_VVERSION_STRING "v0.9.1-1"

namespace QDrive
{
	namespace Version
	{
		int major();
		int minor();
		int release();
		int package();


		bool isDirty();
		QString string();
		QString vString();
	};
};

#endif // QDRIVE_VERSION_H
