/* This file was automatically generated by makeVer v0.2.1-1 */

#include "Version.h"

int QDrive::Version::major()
{
	return 0;
}

int QDrive::Version::minor()
{
	return 9;
}

int QDrive::Version::release()
{
	return 1;
}

int QDrive::Version::package()
{
	return 1;
}





bool QDrive::Version::isDirty()
{
	return false;
}

QString QDrive::Version::string()
{
	return "0.9.1-1";
}

QString QDrive::Version::vString()
{
	return "v0.9.1-1";
}
